application: gorbled
version: 3
runtime: go
api_version: go1
default_expiration: "7d"

handlers:
- url: /static/(.*)
  static_files: gorbled/admin/static/\1
  upload: gorbled/admin/static/(.*)

- url: /([\w]+)/static/(.*)
  static_files: gorbled/templates/\1/static/\2
  upload: gorbled/templates/([\w]+)/static/(.*)

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
